# Generated by Django 2.2.7 on 2019-11-24 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionMemos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_id', models.CharField(max_length=8)),
                ('user_id', models.CharField(max_length=8)),
                ('memo', models.CharField(max_length=200)),
            ],
        ),
    ]
