# Generated by Django 2.2.7 on 2019-11-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0002_auto_20191125_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionmemos',
            name='connection_id',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='connectionmemos',
            name='user_id',
            field=models.CharField(max_length=9),
        ),
    ]
